apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: office-bulletin-app
parameters:
- name: GIT_URL
  required: true
- name: FRONTEND_DIR
  required: true
  value: frontend
- name: STORAGE_SIZE
  required: true
  value: 1Gi
objects:
  # 1) PVC
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pg-pvc
    spec:
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: ${STORAGE_SIZE}

  # 2) Postgres DC with fsGroup and correct mountPath
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: dc-postgres
    spec:
      replicas: 1
      selector:
        app: postgres
      template:
        metadata:
          labels:
            app: postgres
        spec:
          securityContext:
            fsGroup: 26
          containers:
          - name: postgres
            image: postgres:13
            env:
            - name: POSTGRES_DB
              value: bulletindb
            - name: POSTGRES_USER
              value: bulletin
            - name: POSTGRES_PASSWORD
              value: bulletinpass
            volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          volumes:
          - name: pgdata
            persistentVolumeClaim:
              claimName: pg-pvc
      triggers:
      - type: ConfigChange

  # 3) Postgres Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-postgres
    spec:
      selector:
        app: postgres
      ports:
      - port: 5432
        targetPort: 5432

  # 4) PHP Frontend BuildConfig
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      name: bc-frontend
    spec:
      source:
        type: Git
        git:
          uri: "${GIT_URL}"
        contextDir: "${FRONTEND_DIR}"
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: php:7.4
      output:
        to:
          kind: ImageStreamTag
          name: bulletin-frontend:latest
      triggers:
      - type: GitHub;    github: { secret: webhooksecret }
      - type: Generic;   generic: { secret: webhooksecret }
      - type: ImageChange
      - type: ConfigChange

  # 5) PHP Frontend DC
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: dc-frontend
    spec:
      replicas: 1
      selector:
        app: frontend
      template:
        metadata:
          labels:
            app: frontend
        spec:
          containers:
          - name: php
            image: bulletin-frontend:latest
            env:
            - name: DB_HOST
              value: svc-postgres
            - name: DB_NAME
              value: bulletindb
            - name: DB_USER
              value: bulletin
            - name: DB_PASSWORD
              value: bulletinpass
            ports:
            - containerPort: 8080
      triggers:
      - type: ImageChange
        imageChangeParams:
          automatic: true
          from:
            kind: ImageStreamTag
            name: bulletin-frontend:latest
          containerNames: [ php ]
      - type: ConfigChange

  # 6) Frontend Service & Route
  - apiVersion: v1
    kind: Service
    metadata:
      name: svc-frontend
    spec:
      selector:
        app: frontend
      ports:
      - port: 8080
        targetPort: 8080

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: route-frontend
    spec:
      to:
        kind: Service
        name: svc-frontend
